[package]
name = "simple-crypt-util"
version = "0.1.0"
authors = ["Mathias Svensson <freaken@freaken.dk>"]

[dependencies]
base64 = "0.9.0"
failure = "0.1.1"
libc = "0.2.36"
nix = "0.10.0"
serde = "1.0.27"
serde_bytes = "0.10.3"
sodiumoxide = "0.0.16"
termion = "1.5.1"
