[package]
name = "simple-crypt-util"
version = "0.1.0"
authors = ["Mathias Svensson <freaken@freaken.dk>"]

[dependencies]
serde = "1.0.27"
failure = "0.1.1"
sodiumoxide = "0.0.16"
libc = "0.2.36"
nix = "0.10.0"
serde_bytes = "0.10.3"
base64 = "0.9.0"
